ollama:
  api_key: "api_key"
  #what type of function calling is being used. Set true to tools calls and false to function calls
  use_tools_calls: true
  max_tokens: 20000

user:
  admin_username: adrianchojnicki

sicken:
  temperature: 1
  model: "qwen3.5:9b"
  
  seed: 76
  frequency_penalty: null
  presence_penalty: null
  top_p: null
  top_logprobs: null

log:
  debug: false

mongo:
  host: localhost
  port: 27017
  db: sicken

rabbitmq:
  host: localhost
  port: 5672
  user: sicken-deepseek_llm
  password: password
