deepseek:
  api_key: deepseek_api_key
  
sicken:
  temperature: 0
  model: deepseek-reasoner
  
  seed: 76
  frequency_penalty: null
  presence_penalty: null
  top_p: null
  top_logprobs: null

log:
  debug: false

mongo:
  host: localhost
  port: 27017
  db: sicken

rabbitmq:
  host: localhost
  port: 5672
  user: sicken-classification
  password: password
