openai:
  api_key: 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
  
sicken:
  temperature: 0
  model: gpt-5.4
  
  seed: 76
  frequency_penalty: null
  presence_penalty: null
  top_p: null
  top_logprobs: null

log:
  debug: false

mongo:
  host: localhost
  port: 27017
  db: sicken

rabbitmq:
  host: localhost
  port: 5672
  user: sicken-classification
  password: password
