agent_server:
  host: 10.0.2.1
  port: 9999
  secret: asgafgfadsgdafgrearygtaerhtsaerhsrdhgbsdrgsdgr

log:
  debug: true
    
mongo:
  host: localhost
  port: 27017
  db: sicken

rabbitmq:
  host: localhost
  port: 5672
  user: sicken-agent
  password: password
